version: '3.7'
services:
    master:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
        container_name: master
        environment:
            - cluster.name=elastic-cluster
            - node.name=master
            - node.roles=master
            - bootstrap.memory_lock=true
            - discovery.seed_hosts=master,datanode-europe,datanode-asia
            - xpack.security.enabled=false
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
            - cluster.initial_master_nodes=master
        ulimits: 
            memlock: 
                soft: -1
                hard: -1
        volumes:
            - master-data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - elastic-net
    datanode-europe:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
        container_name: datanode-europe
        environment:
            - cluster.name=elastic-cluster
            - node.name=datanode-europe
            - node.roles=data
            - node.attr.my_zone=europe
            - bootstrap.memory_lock=true
            - discovery.seed_hosts=master,datanode-asia
            - xpack.security.enabled=false
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
            - cluster.initial_master_nodes=master
        ulimits: 
            memlock: 
                soft: -1
                hard: -1
        volumes:
            - datanode-europe-data:/usr/share/elasticsearch/data
        networks:
            - elastic-net
    datanode-asia:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
        container_name: datanode-asia
        environment:
            - cluster.name=elastic-cluster
            - node.name=datanode-asia
            - node.roles=data
            - node.attr.my_zone=asia
            - bootstrap.memory_lock=true
            - discovery.seed_hosts=master,datanode-europe
            - xpack.security.enabled=false
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
            - cluster.initial_master_nodes=master
        ulimits: 
            memlock: 
                soft: -1
                hard: -1
        volumes:
            - datanode-asia-data:/usr/share/elasticsearch/data
        networks:
            - elastic-net
    kibana: 
        image: docker.elastic.co/kibana/kibana:8.13.4
        container_name: kibana
        environment:
            - ELASTICSEARCH_HOSTS=http://master:9200
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 5602:5601
        networks:
            - elastic-net

    logstash:
        image: docker.elastic.co/logstash/logstash:8.13.4
        container_name: logstash
        environment:
            - XPACK_MONITORING_ENABLED=false
        ports:
            - "5044:5044"
        volumes:
            - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
            - ./logstash/pipeline:/usr/share/logstash/pipeline
        networks:
            - elastic-net

volumes:
    master-data:
        driver: local
    datanode-europe-data:
        driver: local
    datanode-asia-data:
        driver: local
        
networks:
    elastic-net:
    
